import {
  frontend,
  backend,
  ux,
  prototyping,
  javascript,
  typescript,
  html,
  css,
  reactjs,
  redux,
  tailwind,
  nodejs,
  git,
  figma,
  docker,
  postgresql,
  rubyrails,
  graphql,
  komikult,
  leaderboard,
  math,
  movie,
  nyeusi,
  space,
  coverhunt,
  dcc,
  kelhel,
  microverse,
} from '../assets';

export const navLinks = [
  { id: 'about', title: 'About' },
  { id: 'projects', title: 'Projects' },
  { id: 'contact', title: 'Contact' },
];

const services = [
  { title: 'Business Development', icon: frontend },
  { title: 'Client Relationship Mgmt', icon: backend },
  { title: 'Pre-Sales & Post-Sales', icon: ux },
  { title: 'Market Research & Analysis', icon: prototyping },
];

const technologies = [
  { name: 'Salesforce', icon: html },
  { name: 'Oracle NetSuite ERP', icon: css },
  { name: 'SAP', icon: javascript },
  { name: 'Microsoft D365', icon: typescript },
  { name: 'ZOHO CRM', icon: reactjs },
  { name: 'HubSpot', icon: redux },
  { name: 'LinkedIn Sales Navigator', icon: tailwind },
  { name: 'ZoomInfo', icon: nodejs },
  { name: 'Lusha', icon: rubyrails },
  { name: 'Cold Calling', icon: graphql },
  { name: 'Lead Generation', icon: postgresql },
  { name: 'Account Management', icon: git },
  { name: 'Email Campaigns', icon: figma },
  { name: 'Market Intelligence', icon: docker },
];

const experiences = [
  {
    title: 'Business Development Manager',
    company_name: 'Riveron',
    icon: coverhunt,
    iconBg: '#333333',
    date: 'Aug 2025 - Present',
    description: 'Driving business development and client acquisition initiatives at Riveron.',
  },
  {
    title: 'Business Development Manager',
    company_name: 'Forsys, Inc.',
    icon: coverhunt,
    iconBg: '#333333',
    date: 'Dec 2023 - Mar 2025',
    description: 'Led business development for Oracle and Oracle NetSuite ERP solutions. Drove client acquisition and revenue growth through strategic partnerships and consultative selling.',
  },
  {
    title: 'Business Development Manager',
    company_name: 'Prospecta Software',
    icon: microverse,
    iconBg: '#333333',
    date: 'Aug 2022 - Dec 2023',
    description: 'Managed end-to-end business development for SAP, Oracle, and Oracle NetSuite ERP portfolios. Built strong client relationships with solution architects and delivery teams.',
  },
  {
    title: 'Business Development Manager (Contract)',
    company_name: 'Speridian Technologies',
    icon: kelhel,
    iconBg: '#333333',
    date: 'May 2022 - Oct 2022',
    description: 'Spearheaded sales efforts for ERP solutions. Focused on lead generation, client engagement, and closing key deals.',
  },
  {
    title: 'Business Development Manager',
    company_name: 'ValueLabs',
    icon: dcc,
    iconBg: '#333333',
    date: 'Apr 2021 - Mar 2022',
    description: 'Managed diverse ERP portfolio including SAP, Microsoft D365, Oracle, and NetSuite. Expanded market presence and built enterprise relationships.',
  },
  {
    title: 'Sr. Business Development Executive',
    company_name: 'Idexcel Technologies Pvt Ltd',
    icon: dcc,
    iconBg: '#333333',
    date: 'Nov 2019 - Jan 2021',
    description: 'Focused on mid to enterprise-level clients with ERP needs. Supported pre-sales, proposal creation, and contract negotiations.',
  },
  {
    title: 'Business Development Executive',
    company_name: 'The Global Associates',
    icon: dcc,
    iconBg: '#333333',
    date: 'Aug 2016 - Jul 2019',
    description: 'Worked across multiple verticals to generate leads and qualify opportunities. Developed foundational sales skills and ERP domain knowledge.',
  },
];

const projects = [
  {
    id: 'project-1',
    name: 'ERP Portfolio Growth - Forsys',
    description: 'Led business development initiatives focused on Oracle and Oracle NetSuite ERP, driving client acquisition through consultative selling and strategic partnerships.',
    tags: [
      { name: 'Business Development', color: 'blue-text-gradient' },
      { name: 'Oracle NetSuite', color: 'green-text-gradient' },
      { name: 'Consultative Selling', color: 'pink-text-gradient' },
    ],
    image: komikult,
    repo: '#',
    demo: '#',
  },
  {
    id: 'project-2',
    name: 'Multi-ERP Client Management',
    description: 'Managed SAP, Microsoft D365, Oracle and NetSuite portfolios at ValueLabs, expanding enterprise relationships and market presence.',
    tags: [
      { name: 'SAP', color: 'blue-text-gradient' },
      { name: 'Microsoft D365', color: 'green-text-gradient' },
      { name: 'Enterprise Sales', color: 'pink-text-gradient' },
    ],
    image: leaderboard,
    repo: '#',
    demo: '#',
  },
  {
    id: 'project-3',
    name: 'CRM & ERP Data Integration',
    description: 'Integrated CRM functionality with ERP insights (Salesforce, ZOHO, HubSpot) to generate accurate sales forecasts and unify sales, inventory, and customer service data.',
    tags: [
      { name: 'Salesforce', color: 'blue-text-gradient' },
      { name: 'Data Analysis', color: 'green-text-gradient' },
      { name: 'Sales Forecasting', color: 'pink-text-gradient' },
    ],
    image: math,
    repo: '#',
    demo: '#',
  },
  {
    id: 'project-4',
    name: 'Lead Generation Pipeline',
    description: 'Built prospect database and inside-sales pipeline using email campaigns, cold calling, and social media prospecting across IT Services, Financial Services, Telecom and Automobile verticals.',
    tags: [
      { name: 'Lead Generation', color: 'blue-text-gradient' },
      { name: 'Inside Sales', color: 'green-text-gradient' },
      { name: 'Prospecting', color: 'pink-text-gradient' },
    ],
    image: movie,
    repo: '#',
    demo: '#',
  },
  {
    id: 'project-5',
    name: 'Pre-Sales & Proposal Strategy',
    description: 'Designed viable solutions based on customer requirements, built business proposals, and managed the full pre-sales cycle from qualification to product demonstration.',
    tags: [
      { name: 'Pre-Sales', color: 'blue-text-gradient' },
      { name: 'Proposals', color: 'green-text-gradient' },
      { name: 'Product Demo', color: 'pink-text-gradient' },
    ],
    image: nyeusi,
    repo: '#',
    demo: '#',
  },
];

export { services, technologies, experiences, projects };
